# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_9FAs--IUdHSbBJpk4mWOVQ-avc3xCE
"""

# -*- coding: utf-8 -*-
"""
Main Pipeline Orchestrator Execution - High Performance Run
Executes data processing, model training, and metrics evaluation end-to-end.
"""

import sys
import os
import time

# Ensures Python can find the 'src' folder regardless of execution environment
# sys.path.append(os.path.abspath(os.path.dirname(__file__))) # Removed this line
if '/content' not in sys.path:
    sys.path.append('/content')

from src.data_processing import load_and_process_netflix
from src.model_training import train_funk_svd, build_and_train_ncf
from src.evaluation import evaluate_all_pipelines

def run_pipeline():
    print("🚀 Running High-Performance Recommendation Pipeline...\n")

    # Define dataset path - targets data folder in workspace root or Colab
    dataset_path = "data/combined_data_1.txt"
    if not os.path.exists(dataset_path):
        dataset_path = "/content/data/combined_data_1.txt"

    if not os.path.exists(dataset_path):
        print(f"❌ Error: Missing file at {dataset_path}")
        print("💡 Developer Note: Please make sure you have placed 'combined_data_1.txt' inside a folder named 'data/'.")
        return

    # 1. Load data with healthy interaction frequency thresholds
    train_df, test_df, user_to_idx, movie_to_idx = load_and_process_netflix(
        file_path=dataset_path,
        max_lines=1500000,   # 1.5 Million rows gives an optimal balance of speed and performance
        min_interactions=25  # Prunes highly sparse interactions to clear system noise
    )

    num_users = len(user_to_idx)
    num_movies = len(movie_to_idx)

    # 2. Train Optimized SVD Matrix
    t0 = time.time()
    svd_model = train_funk_svd(train_df)
    svd_time = time.time() - t0

    # 3. Train Bounded Deep Neural Network
    t0 = time.time()
    ncf_model = build_and_train_ncf(
        train_df=train_df,
        num_users=num_users,
        num_movies=num_movies,
        epochs=5,
        batch_size=512
    )
    ncf_time = time.time() - t0

    # 4. Generate Final Metrics Scorecard
    evaluate_all_pipelines(svd_model, ncf_model, test_df)

    print("\n⚡ Execution Performance Summary:")
    print(f"• Funk SVD Training Time: {svd_time:.2f}s")
    print(f"• Deep NCF Training Time: {ncf_time:.2f}s")
    print("\n🏁 Run complete! RMSE optimization successfully finalized.")

if __name__ == "__main__":
    run_pipeline()