# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_9FAs--IUdHSbBJpk4mWOVQ-avc3xCE
"""

# -*- coding: utf-8 -*-
"""
Data Processing Pipeline Module
Handles ingestion, structural line parsing, downcasting, and dense slicing.
"""

import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

def load_and_process_netflix(file_path, max_lines=None, min_interactions=10):
    """
    Parses structural text blocks line-by-line, downcasts to preserve RAM,
    filters out low-frequency noise, and establishes continuous mapping indices.

    Args:
        file_path (str): Path to the raw combined_data_X.txt file.
        max_lines (int, optional): Max lines to read (useful for quick local testing/preview).
                                   Set to None to run on the entire file.
        min_interactions (int): Drop users/movies with fewer interactions than this threshold.
    """
    parsed_rows = []
    current_movie_id = None

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Target raw file not found at: {file_path}. Please check your path configuration.")

    print(f" Processing text rows from {file_path}...")

    # Modular parsing loop
    with open(file_path, 'r') as f:
        for i, line in enumerate(f):
            if max_lines and i > max_lines:
                print(f" Hitting pre-configured line cap limit of {max_lines} rows.")
                break

            line = line.strip()
            if line.endswith(':'):
                current_movie_id = int(line[:-1])
            else:
                row = line.split(',')
                parsed_rows.append([current_movie_id, int(row[0]), int(row[1])])

    # 1. Convert to DataFrame (dropping Date to optimize RAM footprints)
    df = pd.DataFrame(parsed_rows, columns=['Movie_Id', 'Customer_Id', 'Rating'])

    # 2. Memory optimization: Structural data downcasting
    df['Movie_Id'] = df['Movie_Id'].astype('int16')
    df['Customer_Id'] = df['Customer_Id'].astype('int32')
    df['Rating'] = df['Rating'].astype('int8')
    print(f" Parsing complete. Initial base data shape: {df.shape}")

    # 3. Dense Matrix Slicing Core (Removing sparse tail noise)
    if min_interactions > 0:
        user_counts = df['Customer_Id'].value_counts()
        movie_counts = df['Movie_Id'].value_counts()

        df = df[df['Customer_Id'].isin(user_counts[user_counts >= min_interactions].index)]
        df = df[df['Movie_Id'].isin(movie_counts[movie_counts >= min_interactions].index)]
        print(f"✂️ Filtered out instances with < {min_interactions} interactions. Cleaned shape: {df.shape}")

    # 4. Sequential index mapping configurations (Essential for Neural Embeddings)
    user_to_idx = {uid: idx for idx, uid in enumerate(df['Customer_Id'].unique())}
    movie_to_idx = {mid: idx for idx, mid in enumerate(df['Movie_Id'].unique())}

    df['user_idx'] = df['Customer_Id'].map(user_to_idx)
    df['movie_idx'] = df['Movie_Id'].map(movie_to_idx)

    # 5. Continuous Train/Test Partition Split (80/20)
    train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
    print(f" Partitions split successfully: Train={train_df.shape[0]} | Test={test_df.shape[0]}")

    return train_df, test_df, user_to_idx, movie_to_idx


# The code below only runs if you run this script directly (for local testing).
# It will NOT execute automatically when main.py imports this module.
if __name__ == "__main__":
    # Create mock directory logic to test if paths handle cleanly
    os.makedirs('data', exist_ok=True)
    print(" data_processing.py compiled with no functional errors.")