# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_9FAs--IUdHSbBJpk4mWOVQ-avc3xCE
"""

# -*- coding: utf-8 -*-
"""
Recommendation Generation Module
Handles personalization loops and defensive Cold-Start fallback routing.
"""

def generate_user_recommendations(user_id, svd_model, train_df, top_n=10):
    """
    Generates tailored predictions or handles cold-start users gracefully.
    """
    # Cold Start Defense Safeguard
    if user_id not in train_df['Customer_Id'].values:
        print(f"⚠️ Cold-Start Detected for User ID: {user_id}. Routing to Popularity Feed.")
        popular_fallback = train_df.groupby('Movie_Id').agg({'Rating': ['count', 'mean']})
        popular_fallback.columns = ['count', 'mean']
        top_movies = popular_fallback[(popular_fallback['count'] > 50)].sort_values(by=('mean'), ascending=False)
        return top_movies.head(top_n).index.tolist()

    # Personalized Inference Logic
    all_movies = train_df['Movie_Id'].unique()
    rated_movies = train_df[train_df['Customer_Id'] == user_id]['Movie_Id'].values
    unseen_movies = [m for m in all_movies if m not in rated_movies]

    predictions = []
    for mid in unseen_movies:
        est_rating = svd_model.predict(user_id, mid).est
        predictions.append((mid, est_rating))

    predictions.sort(key=lambda x: x[1], reverse=True)
    return predictions[:top_n]